# Generated by Django 2.2 on 2020-02-24 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('image', models.ImageField(blank=True, upload_to='images/books', verbose_name='封面图')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='评分')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '图书信息',
                'verbose_name': '图书信息',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='图书分类名称')),
            ],
            options={
                'verbose_name_plural': '图书分类名称',
                'verbose_name': '图书分类名称',
            },
        ),
    ]
