# Generated by Django 2.2 on 2020-02-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'verbose_name': '图书分类', 'verbose_name_plural': '图书分类'},
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='图书分类'),
        ),
    ]
