# Generated by Django 2.2 on 2020-02-24 04:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
            ],
            options={
                'verbose_name_plural': '文章分类',
                'verbose_name': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2020, 2, 24, 4, 51, 3, 679257, tzinfo=utc), verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('views', models.IntegerField(default=0, verbose_name='阅读人数')),
                ('words', models.IntegerField(default=0, verbose_name='字数')),
                ('status', models.CharField(choices=[('y', '置顶'), ('n', '不置顶')], default='n', max_length=2, verbose_name='是否置顶')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleCategory', verbose_name='文章所属分类')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name_plural': '博客文章信息',
                'verbose_name': '博客文章信息',
            },
        ),
    ]
