# Generated by Django 2.2 on 2020-03-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='网站名称')),
                ('link', models.CharField(default='', max_length=200, verbose_name='网站地址')),
            ],
            options={
                'verbose_name_plural': '友情链接',
                'verbose_name': '友情链接',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(default='https://github.com/wangpeixian', verbose_name='Github地址')),
                ('wechat', models.CharField(default='', max_length=50, verbose_name='微信')),
                ('email', models.CharField(default='', max_length=50, verbose_name='邮箱')),
            ],
            options={
                'verbose_name_plural': '联系方式',
                'verbose_name': '联系方式',
            },
        ),
    ]
