# Generated by Django 2.2 on 2020-03-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_friendlinks_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='github',
            field=models.URLField(default='https://github.com/wangpeixian', verbose_name='Github'),
        ),
    ]
