# Generated by Django 2.2 on 2020-02-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='电影名称')),
                ('director', models.CharField(max_length=100, verbose_name='导演')),
                ('image', models.ImageField(blank=True, upload_to='image/movie', verbose_name='封面图')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='评分')),
                ('release_time', models.DateField(verbose_name='上映时间')),
                ('length_time', models.PositiveIntegerField(default=0, verbose_name='电影时长')),
            ],
            options={
                'verbose_name_plural': '电影',
                'verbose_name': '电影',
            },
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='电影分类')),
            ],
            options={
                'verbose_name_plural': '电影分类',
                'verbose_name': '电影分类',
            },
        ),
    ]
